import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Верхний уровень вручную (3 продукта), внутри — автогенерация по папкам docs.
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Введение',
      collapsed: false,
      link: {type: 'doc', id: 'introduction/index'},
      // Do not use autogenerated here: it would duplicate the linked index doc as a child item.
      items: ['introduction/network-basics', 'introduction/use-cases', 'introduction/limitations'],
    },
    {
      type: 'category',
      label: 'Meshtastic',
      collapsed: false,
      link: {type: 'doc', id: 'meshtastic/index'},
      items: [
        'meshtastic/newbie',
        {
          type: 'category',
          label: 'Настройка ноды',
          link: {type: 'doc', id: 'node-setup/index'},
          items: [
            'node-setup/firmware',
            'node-setup/configuration',
            'node-setup/menu',
            'node-setup/roles',
            'node-setup/testing',
            {
              type: 'category',
              label: 'Драйверы',
              link: {type: 'doc', id: 'node-setup/serial-drivers/index'},
              items: ['node-setup/serial-drivers/esp32', 'node-setup/serial-drivers/nrf52', 'node-setup/serial-drivers/test'],
            },
          ],
        },
        {
          type: 'category',
          label: 'ПО и клиенты',
          link: {type: 'doc', id: 'meshtastic/software/index'},
          items: [
            'meshtastic/software/android',
            'meshtastic/software/apple',
            'meshtastic/software/web-cli',
            'meshtastic/software/integrations',
          ],
        },
        'meshtastic/faq',
        'meshtastic/modules',
        'meshtastic/mqtt',
        'meshtastic/sensors',
        'meshtastic/security',
        {
          type: 'category',
          label: 'Решение проблем',
          link: {type: 'doc', id: 'troubleshooting/index'},
          items: [
            'troubleshooting/not-visible',
            'troubleshooting/radio',
            'troubleshooting/channels',
            'troubleshooting/bluetooth',
            'troubleshooting/flashing',
            'troubleshooting/power',
            'troubleshooting/hardware',
            'troubleshooting/antennas-swr',
            'troubleshooting/network-performance',
          ],
        },
        'community',
      ],
    },
    {
      type: 'category',
      label: 'MeshCore',
      collapsed: false,
      link: {type: 'doc', id: 'meshcore/index'},
      items: [
        'meshcore/newbie',
        {
          type: 'category',
          label: 'Настройка ноды',
          key: 'meshcore_setup',
          link: {type: 'generated-index', slug: '/meshcore/setup', description: 'Прошивка, роли, инфраструктура и эксплуатация: от первого запуска до обновлений.'},
          items: [
            'meshcore/quick-start',
            'meshcore/concepts',
            'meshcore/servers',
            'meshcore/observer',
            'meshcore/bridge',
            'meshcore/t-deck',
            'meshcore/updates',
          ],
        },
        {
          type: 'category',
          label: 'ПО и клиенты',
          key: 'meshcore_software',
          link: {type: 'doc', id: 'meshcore/software/index'},
          items: ['meshcore/software/android', 'meshcore/software/apple', 'meshcore/software/web'],
        },
        'meshcore/faq',
        'meshcore/security',
        'meshcore/troubleshooting',
        'meshcore/ecosystem',
        'meshcore/community',
      ],
    },
    {
      type: 'category',
      label: 'Reticulum',
      collapsed: false,
      link: {type: 'doc', id: 'reticulum/index'},
      items: [],
    },
    'catalog-devices',
    {
      type: 'category',
      label: 'Устройства',
      link: {type: 'doc', id: 'devices/index'},
      items: [
        {
          type: 'category',
          label: 'DIY',
          link: {type: 'doc', id: 'devices/diy/index'},
          items: ['devices/diy/boards'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Антенны',
      link: {type: 'doc', id: 'antennas/index'},
      items: [
        'antennas/types',
        'antennas/ready-made',
        'antennas/connectors',
        'antennas/diy',
        'antennas/check',
        'antennas/nanovna',
        'antennas/spectrum',
        'antennas/mistakes',
      ],
    },
    'glossary',
    'regulations',
  ],
};

export default sidebars;
